PurpleSpider\BasicCalendar\CalendarPage:
  extensions:
    - CustomCalendarPage

PurpleSpider\BasicCalendar\CalendarEntry:
  extensions:
    - CustomCalendarEntry

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - CustomSiteConfig  
